package com.extremerom.xposed.passwordbypass;

// This is a placeholder R class that will be generated by Android build tools
// It contains resource IDs for layouts, strings, etc.
public final class R {
    public static final class layout {
        public static final int activity_main = 0x7f030000;
        public static final int activity_logs = 0x7f030001;
        public static final int item_hook = 0x7f030002;
    }
    
    public static final class id {
        public static final int rvHooks = 0x7f040000;
        public static final int tvModuleStatus = 0x7f040001;
        public static final int tvModuleActive = 0x7f040002;
        public static final int btnViewLogs = 0x7f040003;
        public static final int btnSettings = 0x7f040004;
        public static final int tvHookName = 0x7f040005;
        public static final int tvHookDescription = 0x7f040006;
        public static final int tvInterceptCount = 0x7f040007;
        public static final int tvHookStatus = 0x7f040008;
        public static final int tvClassName = 0x7f040009;
        public static final int tvMethodName = 0x7f04000a;
        public static final int swHookEnabled = 0x7f04000b;
        public static final int llTechnicalDetails = 0x7f04000c;
        public static final int rvLogs = 0x7f04000d;
        public static final int tvEmptyState = 0x7f04000e;
        public static final int spinnerHookFilter = 0x7f04000f;
        public static final int btnClearLogs = 0x7f040010;
        public static final int btnExportLogs = 0x7f040011;
    }
    
    public static final class string {
        public static final int app_name = 0x7f050000;
        public static final int module_description = 0x7f050001;
        public static final int main_title = 0x7f050002;
        public static final int hooks_section = 0x7f050003;
        public static final int no_hooks = 0x7f050004;
        public static final int view_logs = 0x7f050005;
        public static final int settings = 0x7f050006;
        public static final int about = 0x7f050007;
        public static final int hook_enabled = 0x7f050008;
        public static final int hook_disabled = 0x7f050009;
        public static final int intercept_count = 0x7f05000a;
        public static final int logs_title = 0x7f05000b;
        public static final int no_logs = 0x7f05000c;
        public static final int clear_logs = 0x7f05000d;
        public static final int export_logs = 0x7f05000e;
        public static final int filter_by_hook = 0x7f05000f;
        public static final int all_hooks = 0x7f050010;
        public static final int enable_logging = 0x7f050011;
        public static final int logging_description = 0x7f050012;
        public static final int max_logs = 0x7f050013;
        public static final int max_logs_description = 0x7f050014;
        public static final int reset_config = 0x7f050015;
        public static final int reset_config_description = 0x7f050016;
        public static final int confirm_clear_logs = 0x7f050017;
        public static final int confirm_reset_config = 0x7f050018;
        public static final int yes = 0x7f050019;
        public static final int no = 0x7f05001a;
        public static final int cancel = 0x7f05001b;
        public static final int module_status = 0x7f05001c;
        public static final int module_active = 0x7f05001d;
        public static final int module_inactive = 0x7f05001e;
        public static final int xposed_not_active = 0x7f05001f;
        public static final int target_app = 0x7f050020;
        public static final int target_package = 0x7f050021;
        public static final int qa_store_desc = 0x7f050022;
        public static final int cloudgame_desc = 0x7f050023;
        public static final int dev_settings_desc = 0x7f050024;
        public static final int security_warning = 0x7f050025;
        public static final int security_warning_message = 0x7f050026;
        public static final int reboot_required = 0x7f050027;
        public static final int reboot_required_message = 0x7f050028;
    }
    
    public static final class mipmap {
        public static final int ic_launcher = 0x7f060000;
    }
}
